In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import sklearn

In [2]:
print(sklearn.__version__)


1.2.2


In [3]:
data = pd.read_csv("/content/Book1(AutoRecovered).csv")

In [4]:
data.head()

R.N  Id       Date     Time   temp  humidity Surname  L1  L2  L3  ac temp  \
0    1   1  1/12/2023  12:34:56    15        65  keshav   1   1   1       28   
1    2   1  1/13/2023  13:34:56    15        65  keshav   1   1   1       28   
2    3   1  1/14/2023  14:34:56    15        65  keshav   1   1   1       28   
3    4   1  1/15/2023  15:34:56    15        65  keshav   1   1   1       28   
4    5   1  1/16/2023  16:34:56    15        65  keshav   1   1   1       28   

  already present people(id)  
0                        1,2  
1                          0  
2                          0  
3                          2  
4                          0

In [5]:
data

R.N  Id       Date     Time   temp  humidity Surname  L1  L2  L3  ac temp  \
0     1   1  1/12/2023  12:34:56    15        65  keshav   1   1   1       28   
1     2   1  1/13/2023  13:34:56    15        65  keshav   1   1   1       28   
2     3   1  1/14/2023  14:34:56    15        65  keshav   1   1   1       28   
3     4   1  1/15/2023  15:34:56    15        65  keshav   1   1   1       28   
4     5   1  1/16/2023  16:34:56    15        65  keshav   1   1   1       28   
5     6   1  1/17/2023  17:34:56    15        65  keshav   1   1   1       28   
6     7   2  1/18/2023  18:34:56    15        65  akshay   1   0   0       28   
7     8   2  1/19/2023  19:34:56    15        65  akshay   1   0   0       28   
8     9   2  1/20/2023  20:34:56    15        65  akshay   1   0   0       28   
9    10   2  1/21/2023  21:34:56    15        65  akshay   1   0   0       28   
10   11   2  1/22/2023  22:34:56    15        65  akshay   1   0   0       28   
11   12   2  1/23/2023  23:34:56    15        65  akshay   1   0   0       28   

   already present people(id)  
0                         1,2  
1                           0  
2                           0  
3                           2  
4                           0  
5                           1  
6                           0  
7                         1,2  
8                           0  
9                           0  
10                          0  
11                          0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   R.N                         12 non-null     int64 
 1   Id                          12 non-null     int64 
 2   Date                        12 non-null     object
 3   Time                        12 non-null     object
 4   temp                        12 non-null     int64 
 5   humidity                    12 non-null     int64 
 6   Surname                     12 non-null     object
 7   L1                          12 non-null     int64 
 8   L2                          12 non-null     int64 
 9   L3                          12 non-null     int64 
 10  ac temp                     12 non-null     int64 
 11  already present people(id)  12 non-null     object
dtypes: int64(8), object(4)
memory usage: 1.2+ KB


In [7]:
data['Date']=pd.to_datetime(data['Date'])
data['Time ']=pd.to_datetime(data['Time '])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype         
---  ------                      --------------  -----         
 0   R.N                         12 non-null     int64         
 1   Id                          12 non-null     int64         
 2   Date                        12 non-null     datetime64[ns]
 3   Time                        12 non-null     datetime64[ns]
 4   temp                        12 non-null     int64         
 5   humidity                    12 non-null     int64         
 6   Surname                     12 non-null     object        
 7   L1                          12 non-null     int64         
 8   L2                          12 non-null     int64         
 9   L3                          12 non-null     int64         
 10  ac temp                     12 non-null     int64         
 11  already present people(id)  12 non-null     object        
d

In [8]:
data['datequater'] = data['Date'].dt.quarter
data['hour']=data['Time '].dt.hour
data

R.N  Id       Date               Time   temp  humidity Surname  L1  L2  \
0     1   1 2023-01-12 2024-01-22 12:34:56    15        65  keshav   1   1   
1     2   1 2023-01-13 2024-01-22 13:34:56    15        65  keshav   1   1   
2     3   1 2023-01-14 2024-01-22 14:34:56    15        65  keshav   1   1   
3     4   1 2023-01-15 2024-01-22 15:34:56    15        65  keshav   1   1   
4     5   1 2023-01-16 2024-01-22 16:34:56    15        65  keshav   1   1   
5     6   1 2023-01-17 2024-01-22 17:34:56    15        65  keshav   1   1   
6     7   2 2023-01-18 2024-01-22 18:34:56    15        65  akshay   1   0   
7     8   2 2023-01-19 2024-01-22 19:34:56    15        65  akshay   1   0   
8     9   2 2023-01-20 2024-01-22 20:34:56    15        65  akshay   1   0   
9    10   2 2023-01-21 2024-01-22 21:34:56    15        65  akshay   1   0   
10   11   2 2023-01-22 2024-01-22 22:34:56    15        65  akshay   1   0   
11   12   2 2023-01-23 2024-01-22 23:34:56    15        65  akshay   1   0   

    L3  ac temp already present people(id)  datequater  hour  
0    1       28                        1,2           1    12  
1    1       28                          0           1    13  
2    1       28                          0           1    14  
3    1       28                          2           1    15  
4    1       28                          0           1    16  
5    1       28                          1           1    17  
6    0       28                          0           1    18  
7    0       28                        1,2           1    19  
8    0       28                          0           1    20  
9    0       28                          0           1    21  
10   0       28                          0           1    22  
11   0       28                          0           1    23

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype         
---  ------                      --------------  -----         
 0   R.N                         12 non-null     int64         
 1   Id                          12 non-null     int64         
 2   Date                        12 non-null     datetime64[ns]
 3   Time                        12 non-null     datetime64[ns]
 4   temp                        12 non-null     int64         
 5   humidity                    12 non-null     int64         
 6   Surname                     12 non-null     object        
 7   L1                          12 non-null     int64         
 8   L2                          12 non-null     int64         
 9   L3                          12 non-null     int64         
 10  ac temp                     12 non-null     int64         
 11  already present people(id)  12 non-null     object        
 

In [10]:
x= data.iloc[:,[4,5,12,13]].values
#3rd to last-1
y= data.iloc[:,[7,10]].values
#lasrt -1  , dependent ,output , iloc pandas


In [11]:
x

array([[15, 65,  1, 12],
       [15, 65,  1, 13],
       [15, 65,  1, 14],
       [15, 65,  1, 15],
       [15, 65,  1, 16],
       [15, 65,  1, 17],
       [15, 65,  1, 18],
       [15, 65,  1, 19],
       [15, 65,  1, 20],
       [15, 65,  1, 21],
       [15, 65,  1, 22],
       [15, 65,  1, 23]])

In [12]:
y

array([[ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28],
       [ 1, 28]])

In [15]:
from sklearn.datasets import make_regression
from sklearn.datasets import make_regression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [17]:
# Define the base regression model (linear regression in this case)
base_model = LinearRegression()

# Create a multi-output regression model
#multioutput_model = MultiOutputRegressor(base_model)

# Fit the model on the training data
base_model.fit(x, y)

# Make predictions on the test data
#predictions = multioutput_model.predict(X_test)

# Evaluate the model
#mse = mean_squared_error(y_test, predictions)
#print(f'Mean Squared Error: {mse}')
row = [16,62,1,20]
yhat = base_model.predict([row])
# summarize prediction
print(yhat)

[[ 1. 28.]]
